apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test
spec:
  selector:
    matchLabels:
      app: devops-test
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
        - image: aryadi/devops-test:latest
          imagePullPolicy: Always
          name: devops-test
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: devops-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: devops-test

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-test
            port:
              number: 8080